FROM ubuntu:trusty

RUN apt-get update && apt-get install -y git python libssl-dev wget --fix-missing

RUN apt-get install -y software-properties-common vim

RUN apt-add-repository -y ppa:ansible/ansible

RUN apt-get update && apt-get install -y ansible

RUN apt-get update && apt-get install -y python-pip --fix-missing

RUN mkdir -p /root/.aws/ \
    && mkdir -p /root/ansible \
    && pip install boto \
    && pip install boto3

COPY files/credentials /root/.aws/credentials

COPY files/key-us-east-1-default-bastion-01.pem /root/.ssh/id_rsa

COPY playbooks /root/ansible/

WORKDIR /root/ansible
